export const SHOPIFY_COMMERCE_EVENT_SCHEMA_VERSION = 1 as const;

export const SHOPIFY_COMMERCE_EVENT_TYPES = {
  CHECKOUT_OBSERVED: "checkout.observed",
  ORDER_COMPLETED: "order.completed",
} as const;

export const SHOPIFY_WEBHOOK_OUTBOX_DESTINATIONS = {
  CHECKOUT_EVENTS: "CHECKOUT_EVENTS",
  ORDER_EVENTS: "ORDER_EVENTS",
} as const;
